import { ProcessingChain, ChainStep, ChainTarget, ChainLevel, ChainGoal } from '../types';

export const COMPREHENSIVE_GUIDE_CHAINS: ProcessingChain[] = [
  // 1. LEAD VOCAL — AFROBEAT (A CADEIA EXATA SOLICITADA)
  {
    id: 'guide-lead-vocal-afrobeat',
    name: 'Lead Vocal — Afrobeat Masterclass',
    target: 'Lead Vocal',
    style: 'Afrobeat',
    goal: 'Dar presença',
    level: 'Intermediário',
    versionType: 'Completa',
    routingType: 'Serial',
    favorite: true,
    isCustom: false,
    updatedAt: '2026-09-03',
    notes: 'Cadeia de referência para vocal principal de Afrobeat. Limpeza cirúrgica inicial, compressão em duas etapas (transientes + nivelamento), cor analógica e ambiente tridimensional.',
    steps: [
      {
        id: 'step-afro-1',
        order: 1,
        pluginName: 'Clarity Vx',
        manufacturer: 'Waves',
        category: 'Noise Reduction',
        objective: 'Limpar ruído de fundo antes de começar a processar o vocal.',
        whyIsItHere: 'Porque não faz muito sentido comprimir fortemente um vocal cheio de ruído: a compressão pode tornar o ruído muito mais perceptível.',
        whatToHear: 'O ruído de fundo (ar condicionado, hiss do mic, reflexões de quarto) desaparece sem deixar a voz com artefatos robóticos.',
        whatToHearBefore: 'Vocal com ruído constante de fundo, barulho do ventilador/ar condicionado e caixas de som vazando.',
        whatToHearAfter: 'Silêncio cristalino nas pausas entre as frases e voz limpa mantendo todo o ar natural.',
        guideQuestion: {
          question: 'A gravação foi feita numa sala tratada acusticamente e já está 100% silenciosa?',
          ifYes: 'Podes ignorar este plugin para poupar latência e processamento.',
          ifNo: 'Mantém o Clarity Vx ligado com o botão central entre 15% e 35%.',
        },
        pedagogicalTip: 'A Waves descreve o Clarity Vx como uma ferramenta neural para remoção de ruído vocal em tempo real sem alterar a fase das frequências fundamentais.',
        whenNotToUse: 'Se o áudio capturado foi gravado num estúdio profissional tratado sem qualquer ruído ambiente.',
        alternatives: {
          pro: 'Waves Clarity Vx Pro',
          alt: 'iZotope RX Voice De-noise',
          free: 'Bertom Denoiser',
          native: 'Edison Denoise (FL Studio) / Logic Voice De-noise',
        },
        techniqueTip: 'Gira o botão até o ruído sumir. Se a voz soar emborrachada, recua 10%.',
        routingDetails: {
          type: 'Serial',
          notes: 'Primeiro slot do canal da track de gravação.',
        },
      },
      {
        id: 'step-afro-2',
        order: 2,
        pluginName: 'FabFilter Pro-Q 4',
        manufacturer: 'FabFilter',
        category: 'EQ',
        objective: 'Corrigir frequências problemáticas e excessos de gravação.',
        whyIsItHere: 'Investigar excesso de grave, caixa (boxiness nos 300-500Hz), nasalidade (800-1200Hz), dureza (2.5k-4kHz) e sibilância antes de qualquer compressão.',
        whatToHear: 'Voz enxuta, clara e focada no centro tonal da música, sem ressonâncias desagradáveis que incomodem os ouvidos.',
        whatToHearBefore: 'Vocal abafado, embolado com o subgrave do beat e com picos nasais ressonantes.',
        whatToHearAfter: 'Vocal limpo, equilibrado e com espaço garantido para o baixo e o bumbo respirarem.',
        guideQuestion: {
          question: 'O vocal está a soar abafado ou nasalado quando toca junto com o beat?',
          ifYes: 'Ativa uma banda com Q estreito e atenua entre 300Hz e 600Hz de 2 a 3 dB.',
          ifNo: 'Apenas aplica um High Pass Filter suave em 80Hz para cortar subgraves inaudíveis.',
        },
        pedagogicalTip: 'O sistema NÃO deve dizer "Corta exatamente 347 Hz em -4.7 dB". Cada voz e microfone são diferentes. Aprende a varrer a frequência e corta apenas o necessário!',
        whenNotToUse: 'Se a captação foi feita com um microfone de alta qualidade que já soa equilibrado e sem sobras.',
        alternatives: {
          pro: 'FabFilter Pro-Q 4 (Dynamic EQ)',
          alt: 'Waves Renaissance EQ (R-EQ)',
          free: 'TDR Nova (Tokyo Dawn)',
          native: 'Fruity Parametric EQ 2 / Logic Channel EQ',
        },
        techniqueTip: 'High-pass em 80-90Hz (18dB/oct). Se houver ressonância aguda, transforma a banda em dinâmica.',
        routingDetails: {
          type: 'Serial',
          notes: 'Segundo slot da cadeia, pós-limpeza de ruído.',
        },
      },
      {
        id: 'step-afro-3',
        order: 3,
        pluginName: 'CLA-76 (Blacky)',
        manufacturer: 'Waves',
        category: 'Compressor',
        objective: 'Controlar dinâmica de transientes rápidos e trazer o vocal para frente.',
        whyIsItHere: 'A Waves descreve o CLA-76 como inspirado nos compressores de ataque ultra-rápido da era clássica (1176 FET). Ele segura os picos sem esmagar o corpo.',
        whatToHear: 'As consoantes fortes ficam niveladas, e o vocal ganha uma mordida enérgica característica da música moderna.',
        whatToHearBefore: 'Palavras que estouram com volume repentino enquanto frases mais suaves somem no arranjo.',
        whatToHearAfter: 'Picos sob controle firme, voz uniforme e com atitude imediata.',
        guideQuestion: {
          question: 'O vocal tem variações muito bruscas de volume entre frases fortes e fracas?',
          ifYes: 'Aumenta o Input do CLA-76 até obter 3dB a 5dB de redução de ganho nos picos.',
          ifNo: 'Usa compressão mais leve (1dB a 2dB apenas) mantendo o sinal bem transparente.',
        },
        pedagogicalTip: 'Lembra-te: no 1176, o Attack 7 é o mais rápido e o Attack 1 é o mais lento. Usa Attack 3 ou 4 e Release 7 para vocais rápidos.',
        whenNotToUse: 'Se procuras uma balada acústica pura que exija dinâmica intocada.',
        alternatives: {
          pro: 'Universal Audio 1176LN',
          alt: 'FabFilter Pro-C 3 (Modo Punch)',
          free: 'Analog Obsession FETish',
          native: 'Fruity Limiter (Modo Comp Fast) / Logic Studio FET Compressor',
        },
        techniqueTip: 'Ratio 4:1. Ajusta o Output para que o volume com plugin ligado seja idêntico ao desligado (Gain Match).',
        routingDetails: {
          type: 'Serial',
          notes: 'Slot 3: Domando picos rápidos (Catch Peaks).',
        },
      },
      {
        id: 'step-afro-4',
        order: 4,
        pluginName: 'FabFilter Pro-DS',
        manufacturer: 'FabFilter',
        category: 'De-Esser',
        objective: 'Controlar "S", "SH", "T" e outras sibilâncias excessivas.',
        whyIsItHere: 'Após a compressão rápida do 1176, as consoantes sibilantes tendem a saltar para a frente. O Pro-DS doma essas frequências antes da saturação.',
        whatToHear: 'As sibilâncias soam naturais, macias e sem estalar nos fones ou alto-falantes.',
        whatToHearBefore: 'Consoantes agudas cortantes ("S", "C", "T") que machucam os ouvidos em volumes médios/altos.',
        whatToHearAfter: 'Dicção clara e confortável, sem nenhum efeito de ceceio ou abafamento.',
        guideQuestion: {
          question: 'Ao escutar a voz no refrão, o "S" incomoda ou parece uma navalha?',
          ifYes: 'Ajusta o Range no Pro-DS para -3dB a -5dB entre 5.5kHz e 9kHz.',
          ifNo: 'Mantém o De-Esser com sensibilidade suave para atuar apenas em picos imprevistos.',
        },
        pedagogicalTip: 'O Pro-DS é o de-esser dedicado da FabFilter com algoritmo Allround inteligente. Não exageres no threshold para o cantor não soar com a língua presa.',
        whenNotToUse: 'Se a gravação foi feita com microfone de fita (Ribbon) que já tem agudos naturalmente muito escuros.',
        alternatives: {
          pro: 'FabFilter Pro-DS',
          alt: 'Waves Sibilance / Renaissance DeEsser',
          free: 'Techivation T-De-Esser',
          native: 'Fruity Maximus (De-esser preset) / Logic DeEsser',
        },
        techniqueTip: 'Modo Single Vocal, Split Band para atuar apenas nas frequências agudas sem mexer no corpo.',
        routingDetails: {
          type: 'Serial',
          notes: 'Slot 4: Antes do estágio de saturação e nivelamento.',
        },
      },
      {
        id: 'step-afro-5',
        order: 5,
        pluginName: 'Renaissance Vox (R-Vox)',
        manufacturer: 'Waves',
        category: 'Compressor',
        objective: 'Nivelamento e consistência vocal de linha de frente.',
        whyIsItHere: 'Agora que o vocal está limpo e controlado, podes usar uma compressão simples para manter a voz mais consistente e assentada na mix.',
        whatToHear: 'O vocal ganha sustentação, os detalhes de respiração e fim de frase ficam audíveis e o vocal fica colado no centro da música.',
        whatToHearBefore: 'Vocal ainda oscila e perde força quando a percussão densa do Afrobeat entra.',
        whatToHearAfter: 'Vocal firme como uma rocha no centro do arranjo, perfeitamente inteligível.',
        guideQuestion: {
          question: 'O vocal parece que recua na mix quando os metais e percussões entram?',
          ifYes: 'Puxa o fader de Compressão do R-Vox até indicar entre -2dB e -4dB no medidor central.',
          ifNo: 'Mantém uma compressão mínima apenas para nivelar a sustentação final.',
        },
        pedagogicalTip: 'O R-Vox possui uma interface minimalista com algoritmo projetado especificamente para voz, combinando compressão, gate e ganho automático.',
        whenNotToUse: 'Se já usaste um compressor óptico (como CLA-2A) com muita redução no passo anterior.',
        alternatives: {
          pro: 'Waves CLA-2A (Compressor Óptico)',
          alt: 'FabFilter Pro-C 3 (Modo Vocal)',
          free: 'Analog Obsession LALA',
          native: 'Fruity Compressor / Logic Vintage Opto',
        },
        techniqueTip: 'Evita passar de -5dB de redução para não achatar completamente a dinâmica musical.',
        routingDetails: {
          type: 'Serial',
          notes: 'Slot 5: Nivelamento musical do corpo da voz.',
        },
      },
      {
        id: 'step-afro-6',
        order: 6,
        pluginName: 'CLA Vocals',
        manufacturer: 'Waves',
        category: 'Saturation',
        objective: 'Cor, textura analógica e formato estético do vocal.',
        whyIsItHere: 'Adiciona harmônicos analógicos e o timbre característico de produções de grande orçamento (Chris Lord-Alge) para o vocal brilhar no streaming.',
        whatToHear: 'O vocal ganha calor nos médios, um toque sedoso de brilho e presença tridimensional imediata.',
        whatToHearBefore: 'Vocal correto e controlado, mas soando um pouco frio, plano e digital.',
        whatToHearAfter: 'Textura rica, cara, envolvente e pronta para ser tocada na rádio.',
        guideQuestion: {
          question: 'A voz está sem vida ou apagada no meio do beat brilhante?',
          ifYes: 'Ativa o módulo Treble do CLA Vocals em modo Bite e Bass em modo Sub ou Upper.',
          ifNo: 'Usa um saturador sutil como Soundtoys Decapitator com Drive baixo (1.5).',
        },
        pedagogicalTip: 'Se preferires ferramentas individuais, substitui o CLA Vocals por Soundtoys Decapitator (saturação) + Maag EQ4 (Air Band). O CLA Vocals condensa isso em sliders diretos.',
        whenNotToUse: 'Se a voz já foi gravada através de um pré-amplificador valvulado saturado e com distorção excessiva.',
        alternatives: {
          pro: 'Soundtoys Decapitator / FabFilter Saturn 2',
          alt: 'Waves J37 Tape / Abbey Road Saturator',
          free: 'Klanghelm IVGI',
          native: 'Fruity Blood Overdrive (sutil) / Logic Clip Distortion',
        },
        techniqueTip: 'Mantém os faders de Reverb e Delay do CLA Vocals desligados; usaremos canais auxiliares dedicados nos próximos passos para melhor controle.',
        routingDetails: {
          type: 'Serial',
          notes: 'Slot 6: Modelagem tonal e harmônicos.',
        },
      },
      {
        id: 'step-afro-7',
        order: 7,
        pluginName: 'FabFilter Pro-Q 4 (Polimento)',
        manufacturer: 'FabFilter',
        category: 'EQ',
        objective: 'EQ final de polimento, Air Band e equilíbrio pós-saturação.',
        whyIsItHere: 'A saturação gera novos harmônicos. Este EQ dá o polimento estético final (High Shelf em 10kHz-12kHz) e remove qualquer sobra residual.',
        whatToHear: 'Abertura de ar cristalina (sensação de estúdio caro) sem estridência ou aspereza.',
        whatToHearBefore: 'Vocal encorpado porém com pequena sobra de médios-altos da saturação.',
        whatToHearAfter: 'Vocal aberto, moderno e arejado sobrevoando todo o arranjo.',
        guideQuestion: {
          question: 'O vocal precisa daquele ar cristalino moderno para competir com lançamentos de Afrobeat internacionais?',
          ifYes: 'Aplica um High Shelf suave de +1.5dB a +2.0dB em 11kHz com Q suave (0.8).',
          ifNo: 'Deixa flat se o microfone já for excessivamente brilhante.',
        },
        pedagogicalTip: 'O EQ final deve ser musical e com mudanças sutis (geralmente menos de 2.5dB). Se precisares cortar muito aqui, corrige no primeiro Pro-Q 4.',
        whenNotToUse: 'Se a música tiver hi-hats já muito agressivos que estejam a disputar a mesma região de 10kHz.',
        alternatives: {
          pro: 'Maag EQ4 (Air Band lendária)',
          alt: 'Waves SSL E-Channel (High Bell)',
          free: 'Luftikus EQ',
          native: 'Fruity Parametric EQ 2 / Logic Vintage EQ',
        },
        techniqueTip: 'Corta com filtro Low Cut em 85Hz para garantir que nada desceu após os plugins anteriores.',
        routingDetails: {
          type: 'Serial',
          notes: 'Último slot do insert da pista de vocal antes dos sends.',
        },
      },
      {
        id: 'step-afro-8',
        order: 8,
        pluginName: 'ValhallaVintageVerb / Pro-R 2',
        manufacturer: 'Valhalla DSP / FabFilter',
        category: 'Reverb',
        objective: 'Criar espaço tridimensional e ambiência sem turvar o vocal.',
        whyIsItHere: 'Roteado em canal auxiliar (Send) para que o sinal limpo da voz permaneça 100% no centro, enquanto a cauda de reverb é filtrada e envolvente.',
        whatToHear: 'Uma cauda rica, quente e elegante que posiciona o cantor num ambiente acústico nobre, sem embolar o centro mono.',
        whatToHearBefore: 'Vocal seco, desconectado do beat e soando isolado ou colado demais aos ouvidos.',
        whatToHearAfter: 'O vocal integra-se musicalmente com os instrumentos como se tivessem sido gravados no mesmo espaço acústico.',
        guideQuestion: {
          question: 'O reverb está a deixar a mixagem embolada ou a voz parece longe demais?',
          ifYes: 'Aplica a técnica Abbey Road: corta os graves do reverb abaixo de 400Hz e os agudos acima de 6kHz.',
          ifNo: 'Ajusta o fader de envio (Send) até sentires o reverb quando pausas o playback.',
        },
        pedagogicalTip: 'Regra de ouro: regula o reverb até começares a ouvi-lo claramente, e depois abaixa 1.5 a 2dB. O reverb perfeito sente-se quando desligas o bypass!',
        whenNotToUse: 'Em seções secas intimistas onde o objetivo é sussurro no ouvido do ouvinte.',
        alternatives: {
          pro: 'FabFilter Pro-R 2 / LiquidSonics Seventh Heaven',
          alt: 'Waves Renaissance Reverb / Soundtoys Little Plate',
          free: 'Valhalla Supermassive',
          native: 'Fruity Reeverb 2 / Logic ChromaVerb',
        },
        techniqueTip: 'Predelay em 20ms a 40ms para que as consoantes da voz passem limpas antes do reverb abrir.',
        routingDetails: {
          type: 'Send / Aux',
          busName: 'AUX 1 — VOCAL REVERB',
          notes: 'Canal auxiliar com 100% Wet e Low/High Cut nos retornos.',
        },
      },
      {
        id: 'step-afro-9',
        order: 9,
        pluginName: 'EchoBoy / Waves H-Delay',
        manufacturer: 'Soundtoys / Waves',
        category: 'Delay',
        objective: 'Profundidade rítmica e preenchimento harmônico dos silêncios.',
        whyIsItHere: 'Em canal auxiliar Send, repetições sincronizadas com o tempo da música (1/4 ou 1/8 pontilhado) preenchem os vazios entre versos sem disputar atenção com a fala.',
        whatToHear: 'Ecos musicais que dançam no tempo do ritmo e mantêm o fluxo melódico vivo.',
        whatToHearBefore: 'Silêncios entre frases parecem vazios ou perdem a energia do groove.',
        whatToHearAfter: 'Profundidade tridimensional contínua com repetições envolventes que mantêm o ouvinte preso à música.',
        guideQuestion: {
          question: 'O delay está a sobrepor-se às palavras seguintes da letra?',
          ifYes: 'Ativa Sidechain / Ducking no canal do Delay acionado pelo vocal lead, para o delay baixar enquanto o vocal fala e subir nos silêncios.',
          ifNo: 'Automatiza o envio (Send) apenas nas últimas palavras de cada estrofe de impacto.',
        },
        pedagogicalTip: 'O delay moderno de Afrobeat usa frequentemente ping-pong suave filtrado com filtro telefônico (band-pass) para não chocar com as frequências do lead.',
        whenNotToUse: 'Em partes cantadas em andamento muito rápido onde as palavras são contínuas sem espaço.',
        alternatives: {
          pro: 'Soundtoys EchoBoy',
          alt: 'Waves H-Delay / Valhalla Delay',
          free: 'Baby Audio Comeback Kid (Free) / Valhalla Freq Echo',
          native: 'Fruity Delay 3 / Logic Stereo Delay',
        },
        techniqueTip: 'Feedback moderado (3 a 4 repetições). Filtro High Cut em 4.5kHz e Low Cut em 350Hz.',
        routingDetails: {
          type: 'Send / Aux',
          busName: 'AUX 2 — VOCAL DELAY (Ducked)',
          notes: 'Canal auxiliar com Ducking automático via Sidechain.',
        },
      },
    ],
  },

  // 2. KICK — BATERIA & PERCUSSÃO
  {
    id: 'guide-kick-afrobeat-trap',
    name: 'Kick — Punch & Definição',
    target: 'Kick',
    style: 'Afrobeat',
    goal: 'Dar corpo',
    level: 'Intermediário',
    versionType: 'Completa',
    routingType: 'Serial',
    favorite: true,
    isCustom: false,
    updatedAt: '2026-09-03',
    notes: 'Cadeia de bumbo focada em soco no peito, transiente limpo e espaço cirúrgico para a convivência pacífica com o 808 ou Baixo.',
    steps: [
      {
        id: 'step-kick-1',
        order: 1,
        pluginName: 'FabFilter Pro-Q 4',
        manufacturer: 'FabFilter',
        category: 'EQ',
        objective: 'Corte de sub-graves inaudíveis e limpeza de caixa oca.',
        whyIsItHere: 'Remove energias sub-sônicas abaixo de 28Hz que gastam headroom dos alto-falantes e limpa a região de 300Hz-450Hz (som de caixa de papelão).',
        whatToHear: 'O bumbo fica firme, focado e sem peso de lama desnecessário.',
        whatToHearBefore: 'Kick frouxo, com ressonâncias que embolam os fones de ouvido.',
        whatToHearAfter: 'Punch sólido, impacto seco e definição na frequência fundamental (50Hz-65Hz).',
        guideQuestion: {
          question: 'O bumbo soa oco como se estivesses a bater numa caixa de papelão?',
          ifYes: 'Faz um corte moderado com banda estreita na região entre 300Hz e 400Hz (-3dB a -4dB).',
          ifNo: 'Apenas aplica o High Pass em 28Hz e boost sutil de 1dB na fundamental.',
        },
        pedagogicalTip: 'Nunca aumentes graves cegamente. Cortar as frequências médias problemáticas faz o grave do bumbo soar muito mais evidente!',
        whenNotToUse: 'Se o sample do bumbo já veio pré-mixado e processado com perfeição.',
        alternatives: {
          pro: 'FabFilter Pro-Q 4',
          alt: 'Waves SSL E-Channel EQ',
          free: 'TDR Nova',
          native: 'Fruity Parametric EQ 2',
        },
      },
      {
        id: 'step-kick-2',
        order: 2,
        pluginName: 'SPL Transient Designer',
        manufacturer: 'Plugin Alliance',
        category: 'Utility',
        objective: 'Modelar o ataque (Snap) e a cauda (Sustain).',
        whyIsItHere: 'Permite aumentar o soco inicial (transiente) para cortar o beat sem precisar de compressão pesada.',
        whatToHear: 'O kick estala com impacto rápido no início de cada batida.',
        whatToHearBefore: 'Kick afundado atrás dos sintetizadores e guitarras.',
        whatToHearAfter: 'Kick bate com clareza imediata e cauda controlada.',
        guideQuestion: {
          question: 'O kick dura muito tempo e invade o espaço do 808?',
          ifYes: 'Reduz o Sustain em -2dB a -4dB para encurtar a cauda.',
          ifNo: 'Aumenta ligeiramente o Attack em +2dB para dar soco inicial.',
        },
        pedagogicalTip: 'Transient designers são mais transparentes que compressores para bateria porque operam independentemente do nível de volume (threshold-free).',
        whenNotToUse: 'Se o kick já possui transiente excessivo e pontudo.',
        alternatives: {
          pro: 'Oeksound Spiff / SPL Transient Plus',
          alt: 'Waves Smack Attack',
          free: 'Auburn Sounds Couture',
          native: 'Fruity Transient Processor / Logic Enveloper',
        },
      },
      {
        id: 'step-kick-3',
        order: 3,
        pluginName: 'FabFilter Saturn 2',
        manufacturer: 'FabFilter',
        category: 'Saturation',
        objective: 'Saturação de fita para trazer harmônicos audíveis em pequenos fones.',
        whyIsItHere: 'Gera harmônicos suaves que tornam o bumbo audível em celulares e notebooks sem aumentar os picos de decibéis.',
        whatToHear: 'Textura analógica quente e firme.',
        whatToHearBefore: 'Kick audível apenas com subwoofer ou grandes caixas de estúdio.',
        whatToHearAfter: 'Kick perfeitamente perceptível em qualquer dispositivo de áudio.',
        guideQuestion: {
          question: 'Queres um kick moderno com textura de fita clássica?',
          ifYes: 'Usa estilo Warm Tape ou Tube com Drive em 15% e mix em 50%.',
          ifNo: 'Mantém a saturação desligada se procuras som puramente acústico limpo.',
        },
        pedagogicalTip: 'A saturação atua como um limitador suave natural, arredondando os picos mais rápidos.',
        whenNotToUse: 'Se o bumbo começar a chiar ou perder a pureza do grave.',
        alternatives: {
          pro: 'Soundtoys Decapitator',
          alt: 'Waves Kramer Tape',
          free: 'Klanghelm IVGI',
          native: 'Fruity WaveShaper',
        },
      },
      {
        id: 'step-kick-4',
        order: 4,
        pluginName: 'StandardCLIP / Pro-L 2',
        manufacturer: 'SIR Audio Tools / FabFilter',
        category: 'Clipper',
        objective: 'Ceifar picos de transientes milimétricos e ganhar headroom.',
        whyIsItHere: 'Um clipper suave apara 1dB a 2dB do topo pontiagudo do kick sem distorção perceptível, liberando espaço valioso na mixagem para os outros instrumentos.',
        whatToHear: 'Kick com teto uniforme e potente sem clipar o canal master.',
        whatToHearBefore: 'Picos altos no medidor que ativam limitadores cedo demais na masterização.',
        whatToHearAfter: 'Volume percebido mais alto com sinal seguro e controlado.',
        guideQuestion: {
          question: 'O medidor do kick está a bater em +2dB no canal?',
          ifYes: 'Puxa o clip threshold até absorver 1.5dB nos picos.',
          ifNo: 'Mantém o teto em -0.3dB.',
        },
        pedagogicalTip: 'O Soft Clipping é o segredo dos produtores de topo para conseguir beats altos e com impacto sem distorcer na master.',
        whenNotToUse: 'Se aplicaste compressão pesada no passo anterior.',
        alternatives: {
          pro: 'Kazrog KClip 3',
          alt: 'Venn Audio Free Clip',
          free: 'GClip',
          native: 'Fruity Soft Clipper',
        },
      },
    ],
  },

  // 3. BASS / 808
  {
    id: 'guide-bass-808-master',
    name: '808 & Baixo — Graves Sólidos & Celular',
    target: 'Bass',
    style: 'Trap',
    goal: 'Dar corpo',
    level: 'Intermediário',
    versionType: 'Completa',
    routingType: 'Serial',
    favorite: true,
    isCustom: false,
    updatedAt: '2026-09-03',
    notes: 'Cadeia de 808 e Baixo com corte subgrave, mono abaixo de 100Hz, saturação para pequenos alto-falantes e sidechain sincronizado com o Kick.',
    steps: [
      {
        id: 'step-b-1',
        order: 1,
        pluginName: 'FabFilter Pro-Q 4',
        manufacturer: 'FabFilter',
        category: 'EQ',
        objective: 'Filtro subgrave, mono nos graves e separação do Kick.',
        whyIsItHere: 'Corte High-Pass em 25Hz para economizar energia do amplificador. Ativação de corte Mid/Side para manter 100% dos graves abaixo de 100Hz em mono rígido.',
        whatToHear: 'Graves focados no meio exato dos monitores, sem cancelamento de fase estéreo.',
        whatToHearBefore: 'Grave disperso nos lados, instável e consumindo headroom desnecessário.',
        whatToHearAfter: 'Subgrave sólido e centralizado como uma rocha.',
        guideQuestion: {
          question: 'O bumbo bate na mesma frequência exata da nota fundamental do baixo?',
          ifYes: 'Abre um notch dinâmico no Pro-Q 4 na frequência do bumbo (ex: 55Hz) para ceder espaço milimétrico.',
          ifNo: 'Mantém a curva suave.',
        },
        pedagogicalTip: 'Graves abaixo de 90Hz devem quase sempre estar em mono para evitar cancelamento de fase em sistemas de som de clubes e carros.',
        whenNotToUse: 'Se estás a mixar um baixo stereo sintetizado em seções específicas de breakdown.',
        alternatives: {
          pro: 'FabFilter Pro-Q 4 (Linear Phase)',
          alt: 'Brainworx bx_subfilter',
          free: 'TDR Nova',
          native: 'Fruity Parametric EQ 2',
        },
      },
      {
        id: 'step-b-2',
        order: 2,
        pluginName: 'Soundtoys Decapitator',
        manufacturer: 'Soundtoys',
        category: 'Saturation',
        objective: 'Saturação harmônica para audibilidade em smartphones e fones simples.',
        whyIsItHere: 'Cria harmônicos de segunda e terceira ordem entre 250Hz e 800Hz. Isso permite ao ouvinte reconhecer a melodia da nota do 808 mesmo no alto-falante de um celular.',
        whatToHear: 'Um rosnado quente e textura aveludada nos médios, mantendo o sub limpo.',
        whatToHearBefore: 'O 808 desaparece completamente quando ouves no smartphone.',
        whatToHearAfter: 'A linha de baixo é cantável e audível em qualquer dispositivo.',
        guideQuestion: {
          question: 'O 808 soa muito fino ou sem atitude?',
          ifYes: 'Usa estilo A ou T no Decapitator com Drive em 2.0 e botão Thump ligado.',
          ifNo: 'Mantém saturação moderada para não soar como guitarra distorcida.',
        },
        pedagogicalTip: 'Usa o botão Low Cut do saturador para não saturar a sub-fundamental (30-40Hz); satura apenas os médios!',
        whenNotToUse: 'Se o objetivo é uma onda senoidal pura e redonda de R&B dos anos 90.',
        alternatives: {
          pro: 'FabFilter Saturn 2',
          alt: 'Waves RBass / Submarine',
          free: 'CamelCrusher',
          native: 'Fruity WaveShaper / Fast Dist',
        },
      },
      {
        id: 'step-b-3',
        order: 3,
        pluginName: 'FabFilter Pro-C 3 (Sidechain)',
        manufacturer: 'FabFilter',
        category: 'Compressor',
        objective: 'Ducking automático quando o Kick bate (Sidechain).',
        whyIsItHere: 'Abaixa o volume do 808/baixo por 20ms a 50ms precisamente quando o bumbo ataca, evitando a colisão mortal de graves.',
        whatToHear: 'O Kick bate com todo o impacto e o 808 entra logo a seguir com fluidez e groove.',
        whatToHearBefore: 'Kick e 808 batem juntos, causando distorção e cancelamento nos alto-falantes.',
        whatToHearAfter: 'Clube e batida respiram juntos com sensação profissional de pista de dança.',
        guideQuestion: {
          question: 'O bumbo e o 808 tocam exatamente no mesmo instante da batida?',
          ifYes: 'Configura o sidechain do compressor para receber o sinal do Kick e atenua 3dB a 5dB com release rápido.',
          ifNo: 'Se os dois nunca tocam juntos na música, podes ignorar o sidechain.',
        },
        pedagogicalTip: 'O sidechain pode ser feito com compressor ou com plugins dedicados como LFO Tool / Kickstart / Duck. O importante é o release estar afinado no andamento do beat.',
        whenNotToUse: 'Quando o bumbo e o baixo estão em faixas de frequência completamente separadas.',
        alternatives: {
          pro: 'Cableguys VolumeShaper / LFO Tool',
          alt: 'Waves C6 (Sidechain Band)',
          free: 'TDR Kotelnikov',
          native: 'Fruity Limiter (Comp Sidechain)',
        },
      },
      {
        id: 'step-b-4',
        order: 4,
        pluginName: 'FabFilter Pro-L 2',
        manufacturer: 'FabFilter',
        category: 'Clipper',
        objective: 'Teto de picos rígido e consistente.',
        whyIsItHere: 'Garante que nenhuma nota do 808 ultrapasse o teto estabelecido, dando consistência milimétrica.',
        whatToHear: 'Cada nota do baixo com a mesma energia e solidez do início ao fim do refrão.',
        whatToHearBefore: 'Algumas notas graves soam muito mais altas que outras dependendo da altura da escala.',
        whatToHearAfter: 'Graves nivelados, imponentes e comerciais.',
        guideQuestion: {
          question: 'Notas agudas do baixo estão a soar desiguais em relação às graves?',
          ifYes: 'Ajusta o limitador para segurar 1dB a 2dB nas notas mais salientes.',
          ifNo: 'Mantém o teto transparente.',
        },
        pedagogicalTip: 'Use limitador rápido para não criar bombeamento sonoro indesejado no baixo.',
        whenNotToUse: 'Se já controlaste a dinâmica no instrumento virtual de origem.',
        alternatives: {
          pro: 'StandardCLIP',
          alt: 'Waves L2',
          free: 'Venn Audio Free Clip',
          native: 'Fruity Soft Clipper',
        },
      },
    ],
  },

  // 4. MIX BUS — O BUS FINAL DA MÚSICA
  {
    id: 'guide-mix-bus-glue',
    name: 'Mix Bus — A Cola Analógica da Mixagem',
    target: 'Mix Bus',
    style: 'Afrobeat',
    goal: 'Controlar dinâmica',
    level: 'Avançado',
    versionType: 'Completa',
    routingType: 'Serial',
    favorite: true,
    isCustom: false,
    updatedAt: '2026-09-03',
    notes: 'A cadeia do Mix Bus reúne todos os instrumentos e vocais antes da masterização. O objetivo aqui é colar os elementos, adicionar calor de console e controlar dinâmicas microscópicas.',
    steps: [
      {
        id: 'step-mb-1',
        order: 1,
        pluginName: 'FabFilter Pro-Q 4 (Linear Phase)',
        manufacturer: 'FabFilter',
        category: 'EQ',
        objective: 'Corte suave de frequências inaudíveis e limpeza geral.',
        whyIsItHere: 'Filtro High-Pass em 20Hz em modo Linear Phase para não distorcer as relações de fase entre pistas graves. Corte suave de 0.5dB a 1dB onde houver excesso geral.',
        whatToHear: 'Mixagem mais limpa, equilibrada e respirando com clareza.',
        whatToHearBefore: 'Energia fantasma abaixo de 20Hz roubando potência do amplificador.',
        whatToHearAfter: 'Headroom recuperado e graves transparentes.',
        guideQuestion: {
          question: 'A mixagem no geral soa um pouco abafada ou escura?',
          ifYes: 'Aplica um High Shelf suave de +0.5dB em 12kHz com Q largo.',
          ifNo: 'Não forces mudanças extremas no Mix Bus; se precisares de mais de 2dB, ajusta nas pistas individuais.',
        },
        pedagogicalTip: 'No Mix Bus, movimentos de 0.5dB têm impacto colossal. Pensa em milímetros, não em centímetros!',
        whenNotToUse: 'Se as pistas individuais ainda não foram equilibradas.',
        alternatives: {
          pro: 'Brainworx bx_digital V3',
          alt: 'SlickEQ M (TDR)',
          free: 'TDR Nova',
          native: 'Fruity Parametric EQ 2 (HQ mode)',
        },
      },
      {
        id: 'step-mb-2',
        order: 2,
        pluginName: 'SSL G-Master Bus Compressor',
        manufacturer: 'SSL / Waves',
        category: 'Compressor',
        objective: 'A lendária "Cola" (The Glue) de estúdio.',
        whyIsItHere: 'Une a bateria, o baixo, os sintetizadores e os vocais como se pertencessem ao mesmo disco de vinil analógico clássico.',
        whatToHear: 'A música ganha coesão rítmica e passa a mover-se como um único organismo vivo.',
        whatToHearBefore: 'Pistas soam como gravações separadas e desconectadas tocando ao mesmo tempo.',
        whatToHearAfter: 'Pistas coladas com sensação de gravação de grande gravadora.',
        guideQuestion: {
          question: 'Como ajustar o SSL Bus Compressor sem matar a dinâmica da música?',
          ifYes: 'Usa Ratio 2:1 ou 4:1, Attack lento (30ms) para deixar passar o impacto do Kick e Snare, e Release no modo Auto.',
          ifNo: 'A agulha deve mover-se apenas entre 1dB e 2dB nos momentos mais fortes da música.',
        },
        pedagogicalTip: 'Se a agulha passar de 4dB de redução no Mix Bus, estás a esmagar os transientes e a deixar a música sem vida!',
        whenNotToUse: 'Se a música já foi mixada com muita compressão nas pistas individuais.',
        alternatives: {
          pro: 'Cytomic The Glue',
          alt: 'FabFilter Pro-C 3 (Modo Bus)',
          free: 'TDR Kotelnikov (Gentleman)',
          native: 'Fruity Limiter / Logic Vintage VCA Compressor',
        },
      },
      {
        id: 'step-mb-3',
        order: 3,
        pluginName: 'Waves J37 Tape / Saturn 2',
        manufacturer: 'Waves / FabFilter',
        category: 'Saturation',
        objective: 'Aquecimento de fita analógica e saturação harmônica suave.',
        whyIsItHere: 'Simula a passagem do áudio por fita magnética de estúdio (Tape Saturation), arredondando asperezas digitais e adicionando riqueza harmônica.',
        whatToHear: 'Médios sedosos, agudos doces e graves coesos.',
        whatToHearBefore: 'Áudio soando um pouco áspero, frio ou digitalmente estridente nos pratos e voz.',
        whatToHearAfter: 'Sensação aveludada e quente de estúdio clássico.',
        guideQuestion: {
          question: 'Queres a textura dos grandes estúdios analógicos de fita?',
          ifYes: 'Ativa fita a 15 IPS com saturação sutil (menos de 1% THD).',
          ifNo: 'Mantém em bypass se a produção for de música eletrônica ultra limpa e futurista.',
        },
        pedagogicalTip: 'A saturação em bus deve ser quase imperceptível quando ligada, mas sentida com falta quando desligada.',
        whenNotToUse: 'Se a mix já tiver muita distorção acumulada nas pistas.',
        alternatives: {
          pro: 'UAD Studer A800',
          alt: 'Slate Digital VTM',
          free: 'Chow Tape Model',
          native: 'Fruity WaveShaper (curva hiper suave)',
        },
      },
    ],
  },

  // 5. MASTERING — A CADEIA DE SAÍDA FINAL
  {
    id: 'guide-master-commercial-ready',
    name: 'Master — Volume Comercial & Clareza True Peak',
    target: 'Master',
    style: 'Afropop',
    goal: 'Finalizar',
    level: 'Avançado',
    versionType: 'Completa',
    routingType: 'Serial',
    favorite: true,
    isCustom: false,
    updatedAt: '2026-09-03',
    notes: 'Cadeia de masterização completa: EQ de fase linear, controle multibanda, Mid/Side mono em sub, limitador True Peak e medição de LUFS integrado.',
    steps: [
      {
        id: 'step-mst-1',
        order: 1,
        pluginName: 'FabFilter Pro-Q 4 (Linear Phase)',
        manufacturer: 'FabFilter',
        category: 'EQ',
        objective: 'Calibração espectral de alta precisão e mono nos graves.',
        whyIsItHere: 'Opera em modo Linear Phase para garantir que nenhuma alteração de fase borre os transientes da mixagem. Coloca mono abaixo de 90Hz e limpa ressonâncias residuais.',
        whatToHear: 'Equilíbrio tonal perfeito e graves sólidos e consistentes.',
        whatToHearBefore: 'Pequenos desequilíbrios entre estrofes e refrões consumindo volume desnecessário.',
        whatToHearAfter: 'Mixagem polida, limpa e pronta para receber o limitador.',
        guideQuestion: {
          question: 'O refrão está a perder claridade em relação aos lançamentos de referência?',
          ifYes: 'Faz um boost sutil de 0.8dB em 10kHz com banda larga High Shelf.',
          ifNo: 'Mantém as bandas quase flat; o papel da master é calibrar, não refazer a mix!',
        },
        pedagogicalTip: 'A masterização apenas polvilha o que a mix construiu. Se a voz estiver baixa ou o bumbo sem soco, volta e ajusta na mixagem!',
        whenNotToUse: 'Se a mixagem já foi masterizada por outro engenheiro.',
        alternatives: {
          pro: 'Weiss EQ1',
          alt: 'Brainworx bx_digital V3',
          free: 'TDR Nova',
          native: 'Fruity Parametric EQ 2',
        },
      },
      {
        id: 'step-mst-2',
        order: 2,
        pluginName: 'FabFilter Pro-MB',
        manufacturer: 'FabFilter',
        category: 'Compressor',
        objective: 'Controle dinâmico multibanda transparente.',
        whyIsItHere: 'Permite segurar surtos ocasionais de subgrave (abaixo de 80Hz) ou asperezas momentâneas nos agudos (3kHz) sem abaixar a música toda.',
        whatToHear: 'Transições entre partes calmas e explosivas da música soam fluidas e sem solavancos de volume.',
        whatToHearBefore: 'Quando o 808 entra no refrão, a música inteira parece ser comprimida e abaixar.',
        whatToHearAfter: 'O subgrave é domado isoladamente enquanto a voz e os pratos continuam brilhando intactos.',
        guideQuestion: {
          question: 'O subgrave oscila muito dependendo da nota tocada?',
          ifYes: 'Configura uma banda dinâmica no Pro-MB entre 30Hz e 120Hz para atenuar no máximo 1.5dB a 2dB.',
          ifNo: 'Deixa a compressão multibanda em bypass se o equilíbrio já estiver firme.',
        },
        pedagogicalTip: 'Comprimir apenas o que precisa e quando precisa é o maior segredo de masters limpas e competitivas.',
        whenNotToUse: 'Se a mixagem já tiver excelente consistência dinâmica.',
        alternatives: {
          pro: 'Waves C6 Multiband',
          alt: 'Drawmer 1973',
          free: 'TDR Nova (Multiband mode)',
          native: 'Fruity Maximus',
        },
      },
      {
        id: 'step-mst-3',
        order: 3,
        pluginName: 'FabFilter Pro-L 2',
        manufacturer: 'FabFilter',
        category: 'Limiter',
        objective: 'Volume comercial competitivo e proteção True Peak (-1.0 dBTP).',
        whyIsItHere: 'Elevador de volume transparente com algoritmo Modern ou Aggressive, True Peak Limiting ligado e Oversampling 4x para evitar distorção inter-amostras no Spotify, Apple Music e YouTube.',
        whatToHear: 'Volume alto, enérgico, claro e sem estalos ou distorções de clipe digital.',
        whatToHearBefore: 'Música soando baixa em comparação com faixas profissionais da mesma playlist.',
        whatToHearAfter: 'Volume pronto para o mercado comercial, com impacto e dinâmica preservados.',
        guideQuestion: {
          question: 'Qual é o teto (Ceiling) e o alvo de LUFS que deves utilizar?',
          ifYes: 'Ceiling em -1.0 dBTP e alvo de LUFS Integrado entre -10 LUFS e -8 LUFS para Afrobeat/Trap, ou -14 LUFS para plataformas de streaming sem compressão pesada.',
          ifNo: 'Não empurres o Gain além do ponto em que a bateria comece a soar amassada!',
        },
        pedagogicalTip: 'O algoritmo True Peak Limiting do Pro-L 2 recalcula a curva analógica real para que o áudio não distorça quando for convertido para MP3 ou AAC pelas plataformas de streaming.',
        whenNotToUse: 'Nunca entregues uma música sem limitador de segurança na saída.',
        alternatives: {
          pro: 'Weiss MM-1 Mastering Limiter',
          alt: 'Waves L2 / Oxford Limiter',
          free: 'VladG Limiter No6',
          native: 'Fruity Limiter / Logic Adaptive Limiter',
        },
      },
      {
        id: 'step-mst-4',
        order: 4,
        pluginName: 'Youlean Loudness Meter 2 / WLM Plus',
        manufacturer: 'Youlean / Waves',
        category: 'Metering',
        objective: 'Medição precisa de LUFS Integrado, Dynamic Range e True Peak.',
        whyIsItHere: 'Não processa som — apenas mede com precisão matemática as exigências da indústria de streaming e radiodifusão.',
        whatToHear: 'Não altera o som. Monitora visualmente para garantir que o trabalho atinge as metas técnicas.',
        whatToHearBefore: 'Adivinhação às cegas sobre o volume da música.',
        whatToHearAfter: 'Certeza matemática de conformidade com Spotify (-14 LUFS), Apple Music (-16 LUFS) e Clube (-9 LUFS).',
        guideQuestion: {
          question: 'A medição de LUFS Integrado da música inteira está entre -10 e -8.5 LUFS?',
          ifYes: 'Perfeito para Afrobeat, Trap e Pop moderno competitivo.',
          ifNo: 'Se estiver em -6 LUFS está esmagado demais; se estiver em -18 LUFS está muito baixo.',
        },
        pedagogicalTip: 'Coloca o Youlean sempre como o ÚLTIMO plugin do Master. Nada deve vir depois dele!',
        whenNotToUse: 'Nunca omitas um medidor de loudness profissional no seu fluxo de trabalho.',
        alternatives: {
          pro: 'iZotope Insight 2',
          alt: 'Waves WLM Plus Loudness Meter',
          free: 'Youlean Loudness Meter (Free)',
          native: 'Wave Candy (FL Studio) / Logic Loudness Meter',
        },
      },
    ],
  },
  // 6. LEAD VOCAL — SUNO AI AESTHETIC (ABERTO, LIMPO, DUCKED REVERB & MODERN LIMITER)
  {
    id: 'guide-lead-vocal-suno-ai',
    name: 'Lead Vocal — Suno AI Style (Aberto, Limpo, Reverb Largo Ducked & Limiter)',
    target: 'Lead Vocal',
    style: 'Afropop',
    goal: 'Dar brilho',
    level: 'Avançado',
    versionType: 'Completa',
    routingType: 'Sends',
    favorite: true,
    isCustom: false,
    updatedAt: '2026-09-05',
    notes: 'Cadeia de referência inspirada na assinatura sonora de mixagem do Suno AI: vocal cristalino super aberto com Air Band, supressão cirúrgica de ressonâncias, compressão transparente, reverb largo com Abbey Road Trick e Sidechain Ducking, finalizado com True Peak Limiter sem sufocar a dinâmica.',
    steps: [
      {
        id: 'step-suno-1',
        order: 1,
        pluginName: 'FabFilter Pro-Q 3 / Native EQ',
        manufacturer: 'FabFilter',
        category: 'EQ',
        objective: 'Gain Staging e limpeza cirúrgica de subgraves e mud antes de comprimir.',
        whyIsItHere: 'O som hiper-limpo do Suno começa com a remoção de energias subgraves inaudíveis que provocariam disparos erráticos nos compressores e deixariam a voz embolada no beat.',
        whatToHear: 'Voz limpa, leve e perfeitamente assentada no centro do beat.',
        whatToHearBefore: 'Vocal pesado, com estrondo de pedestal/pop e sensação de caixa de papelão nos 300Hz-500Hz.',
        whatToHearAfter: 'Voz definida, sem ressonâncias turvas e com espaço livre para o 808 e bumbo respirarem.',
        guideQuestion: {
          question: 'A voz tem ressonância de sala caseira ou sensação de caixa de papelão?',
          ifYes: 'Aplica um filtro High-Pass em 85-95 Hz e atenua 2 a 3 dB com Q de 3.0 entre 300 Hz e 450 Hz.',
          ifNo: 'Mantém apenas o High-Pass suave em 80 Hz.',
        },
        pedagogicalTip: 'Nunca adicione agudos antes de limpar os graves e médios-graves. A sensação de clareza vem primeiro da remoção do que sobra, não apenas de aumentar os agudos.',
        whenNotToUse: 'Se a captação já foi feita com microfone hiper-direcional com corte ativo e sem graves.',
        alternatives: {
          pro: 'FabFilter Pro-Q 3',
          alt: 'Waves Renaissance EQ (R-EQ)',
          free: 'TDR Nova (Tokyo Dawn)',
          native: 'Fruity Parametric EQ 2 / Logic Channel EQ',
        },
        techniqueTip: 'HPF a 88 Hz (18 dB/oct). Dip de -2 dB em 320 Hz e -1.5 dB em 850 Hz se soar anasalada.',
        routingDetails: {
          type: 'Serial',
          notes: 'Slot 1 no canal da pista de voz.',
        },
      },
      {
        id: 'step-suno-2',
        order: 2,
        pluginName: 'Oeksound Soothe2 / Pro-Q 3 Dinâmico',
        manufacturer: 'Oeksound',
        category: 'Dynamic EQ',
        objective: 'Supressão dinâmica inteligente de ressonâncias e aspereza (Harshness).',
        whyIsItHere: 'Como o vocal do Suno tem um brilho extremo no topo, qualquer aspereza nos 2.5 kHz a 5 kHz se tornaria insuportável. O Soothe2 atenua somente os picos ressonantes em tempo real.',
        whatToHear: 'Voz ultra-aveludada e suave que nunca cansa os ouvidos, mesmo quando o cantor atinge notas agudas de peito.',
        whatToHearBefore: 'Agudos duros, pontiagudos e estridentes nas palavras com maior energia vocal.',
        whatToHearAfter: 'Vocal sedoso, equilibrado e pronto para receber excitação harmônica sem machucar o tímpano.',
        guideQuestion: {
          question: 'Sentiste um tom metálico ou pontudo na voz nas frases mais altas?',
          ifYes: 'Ativa o Soothe2 na faixa de 2.5k a 5.5kHz com Depth entre 2.5 e 3.5.',
          ifNo: 'Se a voz for naturalmente escura, podes pular esta etapa ou usar uma banda dinâmica leve no Pro-Q 3.',
        },
        pedagogicalTip: 'Soothe2 ou Dynamic EQ atuam como um assistente cirúrgico invisível: se não houver ressonância no momento, eles não tocam no sinal.',
        whenNotToUse: 'Se a voz foi gravada em microfone de fita suave como Coles 4038 ou Royer R-121.',
        alternatives: {
          pro: 'Oeksound Soothe2',
          alt: 'Baby Audio Smooth Operator',
          free: 'TDR Nova (Dynamic High-Mid Band)',
          native: 'Maximus / Logic Multipressor',
        },
        techniqueTip: 'Depth em 3.0, Sharpness 5.0. Ouça a diferença no botão Delta para garantir que só remove aspereza.',
        routingDetails: {
          type: 'Serial',
          notes: 'Slot 2 no canal de voz.',
        },
      },
      {
        id: 'step-suno-3',
        order: 3,
        pluginName: 'CLA-76 / 1176 FET Compressor',
        manufacturer: 'Waves / Universal Audio',
        category: 'Compressor',
        objective: 'Captura rápida de transientes das consoantes e presença enérgica in-your-face.',
        whyIsItHere: 'O compressor FET atua em microssegundos segurando os transientes iniciais e trazendo o vocal para a linha de frente da mixagem comercial.',
        whatToHear: 'As palavras ganham firmeza, articulação nítida e mordida rítmica.',
        whatToHearBefore: 'Vocal com picos descontrolados que afundam em algumas frases e explodem em outras.',
        whatToHearAfter: 'Energia compacta e consistente, com ataque imediato.',
        guideQuestion: {
          question: 'O vocal está com saltos repentinos de volume nas primeiras consoantes das palavras?',
          ifYes: 'Usa Ratio 4:1, Attack 3-4 e Release 7 (máxima velocidade de recuperação no 1176).',
          ifNo: 'Atenua apenas 1 a 2 dB se a captação original já foi pré-nivelada.',
        },
        pedagogicalTip: 'Lembre-se da pegadinha do 1176: o botão 7 é o mais rápido e o 1 é o mais lento! Release no 7 permite que o compressor solte o sinal a tempo para a próxima sílaba respirar.',
        whenNotToUse: 'Se você deseja uma mixagem acústica onde toda dinâmica deve soar completamente crua.',
        alternatives: {
          pro: 'UAD 1176LN Classic Limiter',
          alt: 'FabFilter Pro-C 3 (Modo Punch)',
          free: 'Analog Obsession FETish',
          native: 'Fruity Limiter (Modo Comp com attack rápido)',
        },
        techniqueTip: 'Calibre o Input para 2 a 4 dB de Gain Reduction nos picos mais fortes.',
        routingDetails: {
          type: 'Serial',
          notes: 'Slot 3 no canal de voz.',
        },
      },
      {
        id: 'step-suno-4',
        order: 4,
        pluginName: 'FabFilter Pro-DS / Waves Sibilance',
        manufacturer: 'FabFilter',
        category: 'De-Esser',
        objective: 'Eliminar sibilâncias agressivas ("S", "T", "CH") antes do excitador de agudos.',
        whyIsItHere: 'Antes de aplicar o Maag EQ4 ou Fresh Air, é imperativo domar os "S" para evitar que o brilho do Suno vire um assobio cortante.',
        whatToHear: 'As consoantes sibilantes soam musicais e naturais, sem sibilar nem cecear.',
        whatToHearBefore: 'Chiados irritantes nos fonemas sibilantes que incomodam quem ouve em fones de ouvido.',
        whatToHearAfter: 'Sibilância domesticada com precisão sem perder a clareza das palavras.',
        guideQuestion: {
          question: 'Ao pronunciar palavras com "S", o nível de agudos salta bruscamente?',
          ifYes: 'Ajuste a faixa de detecção entre 6.0 kHz e 8.8 kHz com Threshold gerando 3 a 5 dB de redução.',
          ifNo: 'Mantenha a redução em apenas 2 dB para segurança.',
        },
        pedagogicalTip: 'O modo "Single Vocal" do FabFilter Pro-DS escuta o contexto da voz e só comprime quando detecta especificamente o fonema sibilante, preservando as vogais abertas.',
        whenNotToUse: 'Se a gravação original já foi de-essada ou gravada sem agudos.',
        alternatives: {
          pro: 'FabFilter Pro-DS',
          alt: 'Waves Sibilance / Weiss Deess',
          free: 'Techivation T-De-Esser',
          native: 'Maximus De-Esser preset',
        },
        techniqueTip: 'Range de 4 dB a 5 dB. Nunca comprima além de 6 dB para não parecer língua presa.',
        routingDetails: {
          type: 'Serial',
          notes: 'Slot 4 no canal de voz.',
        },
      },
      {
        id: 'step-suno-5',
        order: 5,
        pluginName: 'Tube-Tech CL 1B / Teletronix LA-2A',
        manufacturer: 'Softube / Universal Audio',
        category: 'Compressor',
        objective: 'Nivelamento aveludado, aumento de RMS e calor valvulado (Sustain musical).',
        whyIsItHere: 'A técnica serial consagrada: o CLA-76 agarra os picos rápidos; o compressor óptico (LA-2A ou CL 1B) abraça o corpo restante trazendo uma sustentação luxuosa e intimista.',
        whatToHear: 'Voz próxima, aveludada, encorpada e com estabilidade inabalável na mix.',
        whatToHearBefore: 'Vocal com dinâmica um pouco dura e sensação de distanciamento estático.',
        whatToHearAfter: 'Vocal caloroso, íntimo e com sustentação musical natural em cada nota prolongada.',
        guideQuestion: {
          question: 'As notas longas e finais de frase estão desaparecendo atrás do instrumental?',
          ifYes: 'Aumente o ganho de compressão óptica para obter 2 a 3 dB de atenuação suave e contínua.',
          ifNo: 'Mantenha em 1 a 1.5 dB para uma cola sutil.',
        },
        pedagogicalTip: 'Compressores ópticos possuem uma curva de liberação de dois estágios: os primeiros 50% soltam rápido e o restante solta lentamente ao longo de segundos, criando a famosa "musicalidade valvulada".',
        whenNotToUse: 'Se o estilo exigir voz percussiva ultra-seca sem sustentação (ex: rap rápido/drill seco).',
        alternatives: {
          pro: 'Softube Tube-Tech CL 1B',
          alt: 'Waves CLA-2A / R-Vox',
          free: 'Analog Obsession LALA',
          native: 'Logic Vintage Opto / Fruity Compressor',
        },
        techniqueTip: 'Gain Reduction contínua em torno de 2 dB. Ajuste o Make-up Gain para igualar o volume de entrada e saída.',
        routingDetails: {
          type: 'Serial',
          notes: 'Slot 5 no canal de voz.',
        },
      },
      {
        id: 'step-suno-6',
        order: 6,
        pluginName: 'Maag EQ4 (Air Band) + Slate Fresh Air',
        manufacturer: 'Plugin Alliance / Slate Digital',
        category: 'Exciter',
        objective: 'Injeção de oxigênio acústico, Air Band ultra-aberto e brilho cristalino moderno.',
        whyIsItHere: 'A MARCA REGISTRADA DO SUNO: aquele brilho sedoso e aberto acima de 16 kHz que faz a voz flutuar como num disco Pop de topo das paradas.',
        whatToHear: 'A voz ganha um brilho caro e dimensional, como se tivesse sido gravada através de um microfone Neumann U67 com transformador valvulado.',
        whatToHearBefore: 'Vocal com som correto e plano, mas sem aquele brilho comercial que se destaca em celulares e fones.',
        whatToHearAfter: 'Voz ultra-aberta, cristalina, cara e arejada, sem qualquer sensação de peso ou opacidade.',
        guideQuestion: {
          question: 'A voz precisa cortar o instrumental moderno com ar e presença sem soar agressiva?',
          ifYes: 'No Maag EQ4 selecione a banda Air Band em 20 kHz ou 40 kHz e dê +2.5 dB a +3.5 dB de boost. No Fresh Air, use Mid Air em 12% e High Air em 20%.',
          ifNo: 'Use apenas +1.5 dB se o beat for acústico ou intimista.',
        },
        pedagogicalTip: 'O Air Band do Maag tem uma curva em prateleira extremamente ampla que começa suavemente em 10kHz e atinge o pico inaudível nos 40kHz, trazendo brilho aos harmônicos superiores sem distorcer os médios-altos.',
        whenNotToUse: 'Se o vocal original foi gravado em microfone USB barato com agudos já estridentes e sem tratamento.',
        alternatives: {
          pro: 'Plugin Alliance Mäag Audio EQ4',
          alt: 'Pultec EQP-1A (boost em 16 kHz)',
          free: 'Slate Digital Fresh Air (Free)',
          native: 'Fruity Parametric EQ 2 (High Shelf suave)',
        },
        techniqueTip: 'Air Band em 20 kHz (+3 dB). Cuidado para não exagerar no Fresh Air (>35%), pois pode cansar em longas audições.',
        routingDetails: {
          type: 'Serial',
          notes: 'Slot 6 no canal de voz.',
        },
      },
      {
        id: 'step-suno-7',
        order: 7,
        pluginName: 'Valhalla VintageVerb (Send com Sidechain Ducking)',
        manufacturer: 'Valhalla DSP',
        category: 'Reverb',
        objective: 'Ambiência estéreo larga e cinematográfica SEM abafar o vocal seco no centro.',
        whyIsItHere: 'COMO O SUNO CONSEGUE REVERB LARGO SEM ABAFAR: O segredo é criar uma pista de Send Auxiliar com Abbey Road Filtering (corte abaixo de 500 Hz e acima de 7 kHz) seguido de um Compressor acionado via SIDECHAIN pelo vocal principal.',
        whatToHear: 'Enquanto o vocal canta, o reverb baixa 4 a 6 dB (fica discreto e seco na cara). No momento em que o cantor pausa, o reverb abre e se espalha em estéreo largo tridimensional.',
        whatToHearBefore: 'Vocal afundado na lama do reverb, palavras emboladas e perda de foco frontal.',
        whatToHearAfter: 'Vocal seco, nítido e presente na linha de frente, envolvido por uma nuvem sonora luxuosa e tridimensional.',
        guideQuestion: {
          question: 'O vocal parece que está no fundo de uma caverna quando você aumenta o reverb?',
          ifYes: 'Nunca coloque o reverb como insert direto no canal da voz! Crie um canal auxiliar (Send), insira um EQ cortando <500Hz e >7kHz, coloque o Reverb 100% Wet e em seguida um compressor com sidechain vindo do vocal.',
          ifNo: 'Ajuste a quantidade de envio (Send fader) até atingir a profundidade desejada.',
        },
        pedagogicalTip: 'O "Abbey Road Reverb Trick" remove a lama grave (500Hz) e a sibilância refletida (7kHz). O compressor sidechain ducking garante que a voz lead tenha 100% de inteligibilidade o tempo todo.',
        whenNotToUse: 'Se você estiver produzindo um estilo deliberadamente seco como UK Drill clássico.',
        alternatives: {
          pro: 'Valhalla VintageVerb / FabFilter Pro-R 2',
          alt: 'Lexicon PCM Native / Waves H-Reverb',
          free: 'Valhalla Supermassive',
          native: 'Fruity Reeverb 2 (Send com Peak Controller ou Fruity Limiter Sidechain)',
        },
        techniqueTip: 'Decay: 2.8s, Pre-delay: 35ms, Modo: Concert Hall ou Smooth Plate. Compressor Sidechain com 4 dB a 6 dB de Gain Reduction durante a fala.',
        routingDetails: {
          type: 'Send / Aux',
          notes: 'Canal Auxiliar Reverb com entrada Sidechain linkada à pista Lead Vocal.',
        },
      },
      {
        id: 'step-suno-8',
        order: 8,
        pluginName: 'FabFilter Pro-L 2 (Modern / Transparent)',
        manufacturer: 'FabFilter',
        category: 'Limiter',
        objective: 'Elevar o volume comercial competitivo com controle True Peak sem esmagar os transientes.',
        whyIsItHere: 'O limitador final assegura que a mixagem atinja o volume comercial padrão do Suno (-10 a -8 LUFS) mantendo a nitidez, o ar e o punch da voz sem distorções inter-amostra.',
        whatToHear: 'Volume estrondoso, limpo e aberto, sem perda de dinâmica perceptual ou bombeamento audível.',
        whatToHearBefore: 'Música com volume baixo em comparação com faixas comerciais, ou com picos vermelhos clipando no DAC.',
        whatToHearAfter: 'Som sólido, alto, brilhante e seguro para todas as plataformas de streaming (Spotify, Apple Music, YouTube).',
        guideQuestion: {
          question: 'A mixagem soa abafada ou os pratos de bateria começam a chiar quando você aumenta o limiter?',
          ifYes: 'Você está empurrando o ganho além da conta! Mantenha a redução de ganho do limiter em no máximo 1.5 dB a 2.5 dB.',
          ifNo: 'Deixe o Ceiling em -1.0 dBTP para garantir que a compressão MP3/AAC não introduza clipagem digital.',
        },
        pedagogicalTip: 'O estilo "Modern" do FabFilter Pro-L 2 foi projetado especificamente para música contemporânea: ele preserva os transientes agudos do vocal e da caixa sem causar distorção no subgrave.',
        whenNotToUse: 'Nunca deixe uma mixagem master sem limitador com True Peak ativado.',
        alternatives: {
          pro: 'FabFilter Pro-L 2 (Modo Modern)',
          alt: 'Sonnox Oxford Limiter / Ozone Maximizer',
          free: 'VladG Limiter No. 6',
          native: 'Fruity Limiter / Logic Adaptive Limiter',
        },
        techniqueTip: 'Style: Modern, Lookahead: 0.8ms, Attack/Release otimizados, True Peak Limiting ON, Output Ceiling: -1.0 dBTP.',
        routingDetails: {
          type: 'Serial',
          notes: 'Último processador da cadeia master ou barramento final.',
        },
      },
    ],
  },
];

// GENERATOR / MATCHER ENGINE
export function getRecommendedChain(
  target: ChainTarget,
  style: string,
  goal: ChainGoal,
  level: ChainLevel,
  existingChains: ProcessingChain[] = []
): ProcessingChain {
  // 1. Try to find direct match in existing custom/initial chains
  const allAvailable = [...existingChains, ...COMPREHENSIVE_GUIDE_CHAINS];

  // Direct match by target & style
  const exactMatch = allAvailable.find(
    (c) => c.target === target && c.style.toLowerCase() === style.toLowerCase()
  );
  if (exactMatch) {
    return { ...exactMatch, level, goal };
  }

  // Match by target
  const targetMatch = allAvailable.find((c) => c.target === target);
  if (targetMatch) {
    return {
      ...targetMatch,
      style,
      level,
      goal,
      name: `${target} — ${style} (${goal})`,
    };
  }

  // If no direct preset exists for this exact target, build a tailored pedagogical chain!
  return buildTailoredChain(target, style, goal, level);
}

// Tailored chain builder for any studio element, style, goal and level
function buildTailoredChain(
  target: ChainTarget,
  style: string,
  goal: ChainGoal,
  level: ChainLevel
): ProcessingChain {
  const isVocal = target === 'Lead Vocal' || target === 'Backing Vocal' || target === 'Adlibs';
  const isDrums = target === 'Kick' || target === 'Snare' || target === 'Drum Bus';
  const isBass = target === 'Bass';
  const isMaster = target === 'Master' || target === 'Mix Bus';

  const steps: ChainStep[] = [];

  // Step 1: Cleaning / Pre-Processing
  if (isVocal) {
    steps.push({
      id: `gen-${Date.now()}-1`,
      order: 1,
      pluginName: 'Clarity Vx / Noise Reduction',
      manufacturer: 'Waves',
      category: 'Noise Reduction',
      objective: 'Limpeza de ruído ambiente e ressonâncias de sala.',
      whyIsItHere: 'Porque não faz sentido amplificar ruído através da compressão posterior.',
      whatToHear: 'Fundo silencioso com voz preservada.',
      whatToHearBefore: 'Ruído de fundo e vazamento de fones.',
      whatToHearAfter: 'Voz limpa e isolada.',
      guideQuestion: {
        question: 'O áudio capturado foi feito numa sala ruidosa?',
        ifYes: 'Mantém a limpeza entre 15% e 30%.',
        ifNo: 'Ignora este passo se a captação já estiver 100% limpa.',
      },
      pedagogicalTip: 'Não exagere na limpeza para não criar artefatos robóticos.',
      whenNotToUse: 'Em gravações de cabines profissionais sem ruído.',
      alternatives: { pro: 'Waves Clarity Vx Pro', alt: 'iZotope RX Voice De-noise', free: 'Bertom Denoiser', native: 'Edison Denoise' },
    });
  }

  // Step 2: Corrective EQ
  steps.push({
    id: `gen-${Date.now()}-2`,
    order: steps.length + 1,
    pluginName: 'FabFilter Pro-Q 4',
    manufacturer: 'FabFilter',
    category: 'EQ',
    objective: 'EQ Corretivo Cirúrgico.',
    whyIsItHere: isDrums
      ? 'Corte de sub-graves inaudíveis e limpeza de frequências ocas.'
      : isBass
      ? 'High pass cirúrgico e mono nos graves.'
      : 'Corte de subgraves e remoção de frequências nasais ou ásperas.',
    whatToHear: 'Som enxuto e focado no centro tonal.',
    whatToHearBefore: 'Frequências desnecessárias disputando espaço.',
    whatToHearAfter: 'Elemento transparente e pronto para processamento.',
    guideQuestion: {
      question: 'Existem frequências acumuladas ou irritantes?',
      ifYes: 'Atenue 2dB a 3dB com banda cirúrgica moderada.',
      ifNo: 'Aplique apenas o High Pass para liberar headroom.',
    },
    pedagogicalTip: 'O sistema ensina: procura a região problemática e corta apenas o necessário, sem receitas prontas!',
    whenNotToUse: 'Se o som cru já soa perfeito.',
    alternatives: { pro: 'FabFilter Pro-Q 4', alt: 'Waves Renaissance EQ', free: 'TDR Nova', native: 'Fruity Parametric EQ 2' },
  });

  // Step 3: Fast Compression / Dynamics
  steps.push({
    id: `gen-${Date.now()}-3`,
    order: steps.length + 1,
    pluginName: isVocal ? 'CLA-76 (FET Fast Comp)' : isDrums ? 'SSL Channel Strip' : 'CLA-2A / Pro-C 3',
    manufacturer: isVocal ? 'Waves' : isDrums ? 'SSL' : 'Waves',
    category: 'Compressor',
    objective: 'Controle de transientes rápidos e atitude.',
    whyIsItHere: 'Segura os picos momentâneos mais altos para trazer consistência sem achatar o corpo musical.',
    whatToHear: 'Batidas ou palavras niveladas com presença sólida.',
    whatToHearBefore: 'Picos irregulares escapando do mix.',
    whatToHearAfter: 'Transientes domados com atitude analógica.',
    guideQuestion: {
      question: 'O elemento varia muito de intensidade?',
      ifYes: 'Aumenta a compressão gradualmente até 3dB a 4dB de redução.',
      ifNo: 'Usa compressão mais leve (1-2dB) para manter pureza.',
    },
    pedagogicalTip: 'Ajuste o ganho de saída (Make-up Gain) para igualar o volume antes e depois.',
    whenNotToUse: 'Em instrumentos que necessitam de dinâmica 100% livre.',
    alternatives: { pro: 'Universal Audio 1176', alt: 'FabFilter Pro-C 3', free: 'Analog Obsession FETish', native: 'Fruity Limiter / Comp' },
  });

  // Step 4: Musical Saturation / Tone Shaping
  steps.push({
    id: `gen-${Date.now()}-4`,
    order: steps.length + 1,
    pluginName: 'Decapitator / Saturn 2',
    manufacturer: 'Soundtoys / FabFilter',
    category: 'Saturation',
    objective: 'Harmônicos analógicos e calor de console.',
    whyIsItHere: 'Adiciona textura e harmônicos musicais que ajudam o som a cortar a mixagem sem subir o fader de volume.',
    whatToHear: 'Timbre quente, cheio e encorpado.',
    whatToHearBefore: 'Som digital correto porém sem calor de fita ou console.',
    whatToHearAfter: 'Textura profissional de grandes produções.',
    guideQuestion: {
      question: 'O som precisa de mais destaque e calor?',
      ifYes: 'Ativa estilo analógico suave com Drive entre 1.5 e 2.5.',
      ifNo: 'Mantém desligado se procuras transparência acústica total.',
    },
    pedagogicalTip: 'Saturação sutil cria a ilusão de volume sem consumir teto dinâmico.',
    whenNotToUse: 'Se a gravação já tem distorção de entrada.',
    alternatives: { pro: 'Soundtoys Decapitator', alt: 'Waves J37 Tape', free: 'Klanghelm IVGI', native: 'Fruity WaveShaper' },
  });

  // Step 5: Space / Ambience / Polimento
  if (!isBass) {
    steps.push({
      id: `gen-${Date.now()}-5`,
      order: steps.length + 1,
      pluginName: isMaster ? 'FabFilter Pro-L 2 (Limiter)' : 'ValhallaVintageVerb (Send Aux)',
      manufacturer: isMaster ? 'FabFilter' : 'Valhalla DSP',
      category: isMaster ? 'Limiter' : 'Reverb',
      objective: isMaster ? 'Volume comercial competitivo e proteção True Peak.' : 'Espaço 3D e profundidade de estúdio.',
      whyIsItHere: isMaster
        ? 'Garante que a masterização atinja volume de streaming sem distorção inter-amostras.'
        : 'Coloca o elemento dentro de uma sala tridimensional sem turvar o centro da música.',
      whatToHear: isMaster ? 'Volume comercial limpo.' : 'Ambiência suave e acolhedora.',
      whatToHearBefore: isMaster ? 'Música soando baixa.' : 'Elemento colado e seco nos fones.',
      whatToHearAfter: isMaster ? 'Volume competitivo pronto para streaming.' : 'Profundidade espacial elegante.',
      guideQuestion: {
        question: isMaster ? 'Qual é o True Peak máximo?' : 'O reverb está a embolar a mix?',
        ifYes: isMaster ? 'Deixa o teto em -1.0 dBTP.' : 'Corta os graves do reverb abaixo de 400Hz.',
        ifNo: isMaster ? 'Mantenha em -0.5 dBTP.' : 'Ajusta o envio até sentir a cauda sutilmente.',
      },
      pedagogicalTip: 'Em canais auxiliares, mantenha o Mix em 100% Wet e ajuste o envio pelo Send fader.',
      whenNotToUse: 'Em partes ultra secas e minimalistas.',
      alternatives: { pro: 'FabFilter Pro-R 2', alt: 'Waves Renaissance Reverb', free: 'Valhalla Supermassive', native: 'Fruity Reeverb 2' },
    });
  }

  return {
    id: `tailored-${target.toLowerCase().replace(/\s+/g, '-')}-${style.toLowerCase()}-${Date.now()}`,
    name: `${target} — ${style} (${goal})`,
    target,
    style,
    goal,
    level,
    versionType: 'Completa',
    routingType: 'Serial',
    favorite: false,
    isCustom: true,
    updatedAt: new Date().toISOString().split('T')[0],
    notes: `Cadeia gerada sob medida para ${target} no estilo ${style} com foco em "${goal}". Adaptada para nível ${level}.`,
    steps,
  };
}
